### ISSUE TITLE
Typescript definition

### ISSUE THREAD

**Issue by chrispage1** [alexandreDavid/vue3-tour#1]
Nice work on the Vue3 port :)

The only issue I've run into is that there is no Typescript definition for this.$tours. Easily fixed with:

```
import {Tour} from "vue-tour";

declare module "@vue/runtime-core" {
    interface ComponentCustomProperties {
        $tours: Tour[];
    }
}
```

**Comment by alexandreDavid** [comment]
Hi @chrispage1 , thank you for the issue. You can push a PR I will merge it.

**Comment by restimel** [comment]
Hi,
I just pushed a PR about all typescript definitions (not only $tours, but also components and their props)

→ https://github.com/alexandreDavid/vue3-tour/pull/8
