### ISSUE TITLE
[bug] Arrow not showing in Vue3

### ISSUE THREAD

**Issue by frostcodes** [alexandreDavid/vue3-tour#14]
Hi, great job on porting the library to support Vue3.

I noticed that in Vue3, the arrow isn't showing:

![image](https://user-images.githubusercontent.com/26607698/185796215-ecd3fd7d-ec19-42df-bd72-f503ac46c478.png)

Please take a look at it.

**What I noticed is your CSS is not the same as the original vue-tour.**

**Look at from [here ](https://github.com/pulsardev/vue-tour/blob/a6bf7324224f2d817a2ade108e200d03ee391075/src/components/VStep.vue#L225) especially to [here](https://github.com/pulsardev/vue-tour/blob/a6bf7324224f2d817a2ade108e200d03ee391075/src/components/VStep.vue#L270)**.

_**It seems that you should use the SCSS exactly as created in vue-tour.**_

**Comment by alexandreDavid** [comment]
Fixed in 0.3.3
