### ISSUE TITLE
The arrow is hidden inside the step when setting placement to 'right'

### ISSUE THREAD

**Issue by bhaidar** [alexandreDavid/vue3-tour#29]
Hello Alexandre,

I am using vue3-tour in a new Laravel/InertiaJs (Vue) project.

When I place the  step on the `right` using the `placement`property, the arrow is hidden inside the step UI. 

This is the steps definition I have:

```
const steps = [
   {
      target: '#v-step-0',
      content: `..`,
       params: {
           placement: 'right',
        },
  },
]
```

I could change this behavior via CSS but that's cumbersome as I have to do this per step which is not practical.

I am also attaching snapshots on the issue.

Much appreciated your support.

<img width="678" alt="Screenshot 2024-07-12 at 18 20 16" src="https://github.com/user-attachments/assets/d945759e-3275-4ee6-9068-bc6abbb9d957">

Regards
Bill

**Comment by alexandreDavid** [comment]
fix in release [1.0.2](https://github.com/alexandreDavid/vue3-tour/releases/tag/1.0.2)
