### ISSUE TITLE
How to use in Vue3 compostion API as we can't use "this" composition api

### ISSUE THREAD

**Issue by abbasnaumani** [alexandreDavid/vue3-tour#5]
Vue3 composition setup:

setup(){
// Here we can't use this.$tours['myTour'].start(), as we can't find instance in this, so please update

return [];
}

**Comment by talachart** [comment]
> Vue3 composition setup:
> 
> setup(){ // Here we can't use this.$tours['myTour'].start(), as we can't find instance in this, so please update
> 
> return []; }

You should use this method

import {
  getCurrentInstance, defineComponent, onMounted, reactive, toRefs,
} from 'vue';

export default defineComponent({
  setup: () => {
    // init data
    const $vueInstance: any = getCurrentInstance();

    // steps
    const state = toRefs(reactive({
      steps: [
        {
          target: '#step-0',
          header: {
            title: 'Get Started',
          },
          content: 'Discover <strong>Vue Tour</strong>!',
        },
      ],
    }));

    // on mounted
    onMounted(() => {
      $vueInstance?.proxy?.$tours?.myTour?.start();
    });

    // return data
    return {
      ...state,
    };
  },
});

**Comment by restimel** [comment]
I am wondering if it won't be good to add a props to v-tour which will start the tour. For example, `autoplay` (if `true` the tours starts immediately) or `start` (if `true` when mounted or if changing to `true` then it will be equivalent to `this.$tours['myTour'].start()`).
Or a `play` props which will be equivalent to `.start()` or `.stop()` depending on its value.

In my opinion it would be more in the Vue philosophy than calling `$tours[''].start()`.

However if we implement this feature in vue3-tour, there will be a difference with the original vue-tour project. Is it the purpose of this project, or should it be a feature request in vue-tour ?

**Comment by dylanmcgowan** [comment]
Hey y'all, this is how I implemented this package with vue3, hope it helps! No need to make the steps reactive @talachart.

```js
// main.js
import VueTour from 'v3-tour'
app.use(VueTour).provide('tours', app.config.globalProperties.$tours)
```

```vue
<script setup>
import { inject, onMounted } from 'vue'
const tours = inject('tours')

onMounted(() => {
   tours['myTour'].start()
})
</script>
```

**Comment by sajjadalis** [comment]
@dylanmcgowan Can't get it working with script setup. After inject, it still says `tours` is `undefined`. If I `console.log(app.config.globalProperties.$tours)` in main.js. It displays object but provide/inject doesn't work for some reason. That is a very clean solution and would solve issues with other plugins. Any help would be appreciated.

**Comment by Tyrannas** [comment]
Maybe this should be written in the docs ? Since more and more people are using script setup now, it would be nice not to have to digg in the issues

**Comment by Saidmurod1996** [comment]
Why is this closed without being fixed or at least showing the solution?

**Comment by objectamit** [comment]
With the following added to main.js
```vue
import Vue3Tour from 'vue3-tour'
const app = createApp(App)
app.use(Vue3Tour)
``` 
and with vue3 version 3.4.35, I am able to start my tour on click of a button using something like 
```vue
<v-tour name="myTour"></v-tour>
<button @click="$tours['myTour'].start()">Start Tour</button>
```
Please note that the tour component is registered with name v-tour and VTour / VueTour / Vue3Tour component names will not work
