### ISSUE TITLE
Translate button text

### ISSUE THREAD

**Issue by KelvynCarbone** [alexandreDavid/vue3-tour#9]
How change buttons text?

**Comment by alexandreDavid** [comment]
There is a prop options in the VTour which is an object.
Inside, there is a labels property. Free to you to change the default values. 
```js
  labels: {
    buttonSkip: 'Skip tour',
    buttonPrevious: 'Previous',
    buttonNext: 'Next',
    buttonStop: 'Finish'
  }
```
